### ISSUE TITLE
OPT_2: implementation of PSO system

### ISSUE THREAD

**Issue by MatheuBotha** [MatheuBotha/DragonBrain#14]
Implement the neccessary PSO alogs into the architecture 
-CPSO
-FIPS
-gcPSO

**Comment by u14006512** [comment]
PSO Base is done

**Comment by u14006512** [comment]
Implementation of Marsenne Twister pseudo random number system done inside PSO. This is apparently a better random number system than base according to some sources. I've added it here since I know Angel Bright talked about it being a valid approach to generating random numbers.
